### PR TITLE
Add ksp example project

### PR DESCRIPTION
**Pull request by IceBlizz6**

### CODE REVIEW

**Comment by IceBlizz6** [comment]
I'm not sure if it's possible to reference the version build variables from pom in the parent maven project here since this is essentially a standalone gradle project.

**Comment by IceBlizz6** [comment]
If possible i think this project should be added to the build pipeline to ensure we avoid problems like "but it worked on my machine"

**Comment by velo** [comment]
Now we need to run it, similarly to quarkus native example:
https://github.com/OpenFeign/querydsl/blob/master/.circleci/config.yml#L146

> I'm not sure if it's possible to reference the version build variables from pom in the parent maven project here since this is essentially a standalone gradle project.

You would need to export from maven and import on gradle

https://www.mojohaus.org/properties-maven-plugin/write-project-properties-mojo.html

**Comment by IceBlizz6** [comment]
I'm making some progress here.
It will try to pickup version numbers from gradle.properties file, which can be generated from write-project-properties task.
I added this to gitignore.

I was not able to find property for current version (6.9-SNAPSHOT)
Also seemed like there was no property for assertj so i left that as it was.

Next step now is to create a build script, i may need some assistance on that.

I think essentially the flow would be 

1. Run `./mvnw org.codehaus.mojo:properties-maven-plugin:1.2.1:write-project-properties -N -Dproperties.outputFile=querydsl-examples/querydsl-example-ksp-codegen/gradle.properties`
2. Install gradle
3. Run gradle build from the project path of my example

I don't know where i would put this script file or how i would structure it.

**Comment by velo** [comment]
@IceBlizz6 do you think is there anything else we should add to output that might be helpful?
https://app.circleci.com/pipelines/github/OpenFeign/querydsl/2270/workflows/4151d484-4153-4d5a-9c85-a27d70ed2efc/jobs/18557

**Review by velo — APPROVED** [review]

**Comment by velo** [comment]
Also, feel free to add yourself to the contributors list

https://github.com/OpenFeign/querydsl/pull/663/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L37

**Comment by IceBlizz6** [comment]
> do you think is there anything else we should add to output that might be helpful?

Can't think of anything, the output indicates that it's running through all the expected steps so it seems fine.

> Also, feel free to add yourself to the contributors list

Thanks, i think i will do that later.
So it seems like this PR is good to go now?
We can merge it i think.
I see you wrote the buildscript, well done!

**Another important thing:**
I'm sitting on some code changes that solves one big issue and a few small one.
The big issue is that the processor will give a lot of errors if it's used with KSP's incremental compilation.
The code that was merged earlier assumed that all entities were processed together.

You mentioned that you wanted to release next version after this example.
I'm thinking that it may be best to include these fixes in the next release.
So would it be possible to delay it a little bit longer?

I can make a PR for those changes later today.

**Comment by velo** [comment]
> **Another important thing:** I'm sitting on some code changes that solves one big issue and a few small one. The big issue is that the processor will give a lot of errors if it's used with KSP's incremental compilation. The code that was merged earlier assumed that all entities were processed together.
> 
> You mentioned that you wanted to release next version after this example. I'm thinking that it may be best to include the fixes in this next release. So would it be possible to delay it a little bit longer?
> 
> I can make a PR for those changes later today.

Sure, we can delay for another week or so if needed

**Pull request merged**
