### PR TITLE
Add subselect to JPQLRepository

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by anas-zubk-scacap** [comment]
hi! why did you change the return type for `JPQLQuery<T>` to `JPQLSubQuery<T>`? 
I am currently migrating from com.querydsl to github.openfeign.querydsl and this change creates compilation errors. 

How would you suggest I migrate a piece of code like this:

  ```
    private JPQLQuery<String> FunctionName(Arguments) {
        return JPAExpressions.select(String)
                .from(Table)
                .where(Condition))
                .groupBy(Table.String)
                .fetchAll();
    }
    ```
    
In the github.openfeign.querydsl, `JPAExpressions` returns a `JPQLSubQuery` instead of a `JPQLQuery`, which is not an identical implementation to com.querydsl

**Comment by nealeu** [comment]
@velo You criticised the querydsl team for lack of engagement, yet didn't respond here to @anas-zubk-scacap.
I'm tackling the same challenge, migrating from 5 to 6, and should not need to hunt for the PR that introduced the interface that I'm now finding is causing compilation errors.
If you want people like the Spring team to adopt the OpenFeign version then the release plan really needs to focus on getting documentation in order.

**Comment by velo** [comment]
Feel free to send a PR

**Comment by nealeu** [comment]
> Feel free to send a PR

That would require me to understand your intent. I've commented as to what I think the challenge with this change is.

That's why I was suggesting you answer the question: "hi! why did you change the return type for JPQLQuery<T> to JPQLSubQuery<T> for public static <T> JPQLQuery<T> select(Expression<T> expr)?"

**Pull request merged**
