### PR TITLE
The transform method throws a ClassCastException when working with joinFetch since 4.4.0

### PR DESCRIPTION
**Pull request by kamilkrzywanski**
from https://github.com/aasyspl/querydsl
fixes  https://github.com/querydsl/querydsl/issues/3264 (checked with issuer example)

### CODE REVIEW

**Review by velo — CHANGES_REQUESTED** [review]
Hi @kamilkrzywanski , thanks for you efforts on this, can you please also modify the existing unit tests to cover this too?

Thanks

**Comment by kamilkrzywanski** [comment]
@velo 
The attached test may not be the most sophisticated, but it does its job.

**Review by velo — APPROVED** [review]

**Comment by kamilkrzywanski** [comment]
@velo can you create release 5.6 also with this change? 
Thanks in advance :)

**Comment by kamilkrzywanski** [comment]
Probably nothing is stopping me anymore. I'm migrating a huge project to Spring 3 and Hibernate 6, but first, I'd like to be sure that the fork works well with hibernate 5 etc... :)
The draft of migration with QueryDSL 6 is working well so far, by the way. :)
Querydsl is not blocker already, thank you :)

**Pull request merged**
