### PR TITLE
Querydsl JPA <-> spring data repository integration

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by odrotbohm** [comment]
Can someone elaborate what the intention behind this addition to Querydsl is? Spring Data has had support for Querydsl for almost a decade and introducing Spring Data support in Querydsl in turn creates a cyclic dependency, that's going to at least cause versioning trouble for users.

What you've built here is quite anti-idiomatic to the Spring Data repository concept in the first place. Low-level querying functionality belongs *behind* a repository and should not be *exposed* by it. Otherwise, the implementing persistence technology leaks into calling code. The Spring Data idiomatic way is represented in `org.springframework.data.jpa.repository.support.QuerydslRepositorySupport` which seamlessly hooks into the custom implementation repository extension model.

**Comment by velo** [comment]
> Spring Data has had support for Querydsl for almost a decade and introducing Spring Data support in Querydsl in turn creates a cyclic dependency, that's going to at least cause versioning trouble for users.

why?

How come `querydsl-sql-spring` doesn't cause such problem with spring framework itself?


> What you've built here is quite anti-idiomatic to the Spring Data repository concept in the first place

You saying `@Query` should be removed from spring data?  Or in that case `sql` is not low level?

> `QuerydslRepositorySupport `

Ow boy, you know that is a good when you google it and first result is javadoc.

As far I remember from the pain of using `QuerydslRepositorySupport` in the past:

1 - You need to create a class, not an interface like most repositories 
2 - do not seemly integrate with vanilla JPA repository


But, if you don't like there is nothing forcing you to use it, very isolated example.

**Comment by odrotbohm** [comment]
> why? How come querydsl-sql-spring doesn't cause such problem with spring framework itself?

It actually does. I just mentioned Boot and Data explicitly as that are the dependencies you explicitly list and compile against.

> You saying @Query should be removed from spring data? Or in that case sql is not low level?

**Comment by velo** [comment]
image

Well, then it's a 10 years old problem already that I'm inheriting from the original project.

Happy for suggestions on how to solve it, but, I'm not interested in having 2 code bases to maintain.

**Comment by odrotbohm** [comment]
I deliberately decided to remove my comment to not fuel the harsh and polemic tone you initiated [here](https://github.com/OpenFeign/querydsl/pull/141#issuecomment-1913294701). It would be nice of you if you respected that. Thanks! 🙇

**Pull request merged**
