### PR TITLE
Merge using updates to 5.0.0

### PR DESCRIPTION
**Pull request by borgiiri**

### CODE REVIEW

**Review by velo — APPROVED** [review]

**Comment by velo** [comment]
https://github.com/OpenFeign/querydsl/releases/tag/5.1.1

**Comment by borgiiri** [comment]
Thanks!

**Comment by borgiiri** [comment]
> https://github.com/OpenFeign/querydsl/releases/tag/5.1.1

@velo the tag build seemed to pass and it said "Uploading locally staged artifacts to profile io.github.openfeign", however the artifacts did not appear in maven central, do you have ideas what the issue could be?

**Comment by velo** [comment]
https://repo1.maven.org/maven2/io/github/openfeign/querydsl/querydsl-sql/5.1.1/

What is missing from central?

**Comment by borgiiri** [comment]
Oooh, I was checking through https://mvnrepository.com/.
https://mvnrepository.com/artifact/io.github.openfeign.querydsl/querydsl-core
Probably it's slow to refresh or something.

Sorry for disturbing and thanks!

**Pull request merged**
